import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ArrowDownToLine, BadgeCheck, CalendarDays, Camera, Check, ChevronDown, Clock3, Cloud, Fingerprint, History, House, LogIn, LogOut, MapPin, Plus, ScanFace, Settings, ShieldCheck, UserRound, Users, Wifi, X } from 'lucide-react';
import './styles.css';

const STORE='nova-v2-beta';
const shiftDefaults=[{id:'morning',name:'กะเช้า',start:'08:00',end:'17:00',grace:9},{id:'normal',name:'กะปกติ',start:'09:00',end:'18:00',grace:9}];
const initial={employees:[
  {id:'NV001',firstName:'เม่น',nickname:'เม่น',type:'รายเดือน',shift:'normal',note:'',active:true,faceStatus:'ยังไม่ลงทะเบียน'},
  {id:'NV002',firstName:'มิ้นท์',nickname:'มิ้นท์',type:'รายเดือน',shift:'morning',note:'',active:true,faceStatus:'ยังไม่ลงทะเบียน'},
  {id:'NV003',firstName:'มิน',nickname:'มิน',type:'รายเดือน',shift:'morning',note:'',active:true,faceStatus:'ยังไม่ลงทะเบียน'},
  {id:'NV004',firstName:'แป้ง',nickname:'แป้ง',type:'รายเดือน',shift:'normal',note:'',active:true,faceStatus:'ยังไม่ลงทะเบียน'}
],events:[],settings:{worksiteName:'NOVA · คลังสินค้า',latitude:'',longitude:'',radiusKm:'0.10'},shifts:shiftDefaults,holidays:[],role:'user',activeEmployeeId:'NV001'};
const roleNames={superadmin:'Admin ขั้นสูง',peopleadmin:'Admin เพิ่มพนักงาน',user:'พนักงาน'};
const safeLoad=()=>{try{return {...initial,...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return initial}};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const clock=()=>new Intl.DateTimeFormat('th-TH',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date());
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const shiftFor=(state,shiftId)=>state.shifts.find(s=>s.id===shiftId)||state.shifts[1]||shiftDefaults[1];
function App(){
  const [db,setDb]=useState(safeLoad);const [tab,setTab]=useState('home');const [now,setNow]=useState(new Date());const [faceState,setFaceState]=useState('idle');const [faceMsg,setFaceMsg]=useState('เปิดกล้องเพื่อเริ่มตรวจใบหน้า');const [cameraError,setCameraError]=useState('');const [toast,setToast]=useState('');const [form,setForm]=useState({firstName:'',nickname:'',type:'รายเดือน',shift:'normal',note:''});const [holidayForm,setHolidayForm]=useState({date:'',name:'',type:'บริษัท'});const [saving,setSaving]=useState(false);const video=useRef(null),stream=useRef(null),detectLoop=useRef(0),faceTimer=useRef(0);
  const role=db.role,employee=db.employees.find(e=>e.id===db.activeEmployeeId)||db.employees[0];const isAdmin=role!=='user',isSuper=role==='superadmin';
  useEffect(()=>{localStorage.setItem(STORE,JSON.stringify(db))},[db]);useEffect(()=>{const t=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(t)},[]);useEffect(()=>()=>stopCamera(),[]);useEffect(()=>{if(faceState==='camera'&&video.current&&stream.current)video.current.srcObject=stream.current},[faceState]);
  const mine=db.events.filter(e=>e.employeeId===employee?.id&&e.date===today());const pending=db.events.filter(e=>e.status==='pending');
  function notify(s){setToast(s);setTimeout(()=>setToast(''),2800)}
  function stopCamera(){clearTimeout(detectLoop.current);clearTimeout(faceTimer.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null}
  async function startCamera(){setCameraError('');setFaceState('camera');setFaceMsg('กำลังเปิดกล้องและตรวจคุณภาพภาพ');try{if(!navigator.mediaDevices?.getUserMedia)throw Error('เบราว์เซอร์นี้ไม่รองรับกล้อง');stream.current=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}}});faceTimer.current=setTimeout(()=>{stopCamera();setFaceState('idle');setFaceMsg('พักหน้าจอแล้ว · ไม่มีการสแกนใบหน้าต่อเนื่อง 1 นาที')},60000);const detector='FaceDetector'in window?new window.FaceDetector({fastMode:false,maxDetectedFaces:2}):null;if(!detector){setFaceMsg('กล้องเปิดแล้ว แต่ browser นี้ไม่มี face detector — ยังยืนยันตัวตนไม่ได้');return}watchFace(detector)}catch(e){setFaceState('idle');setCameraError(e.message||'เปิดกล้องไม่สำเร็จ กรุณาอนุญาตกล้องและใช้ HTTPS')}}
  async function watchFace(detector){if(!stream.current)return;try{if(video.current?.readyState>=2){const result=await detector.detect(video.current);if(result.length===1){setFaceState('detected');setFaceMsg('ตรวจพบใบหน้า 1 คน · ยังไม่ได้จับคู่กับบัญชีพนักงาน');clearTimeout(faceTimer.current);faceTimer.current=setTimeout(()=>{stopCamera();setFaceState('idle');setFaceMsg('พักหน้าจอแล้ว · ไม่มีการสแกนต่อเนื่อง 1 นาที')},60000)}else if(result.length>1){setFaceState('camera');setFaceMsg('พบหลายใบหน้า กรุณาให้มีเพียงพนักงาน 1 คนในกรอบ')}else{setFaceState('camera');setFaceMsg('ไม่พบใบหน้า · จัดใบหน้าไว้กลางกรอบ')}}}catch{setFaceMsg('ตรวจภาพไม่สำเร็จ')}detectLoop.current=setTimeout(()=>watchFace(detector),700)}
  async function captureEvent(type){if(faceState!=='detected'){notify('ยังตรวจไม่พบใบหน้า');return}const loc=navigator.geolocation?await new Promise(resolve=>navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy}),()=>resolve({lat:null,lng:null,accuracy:null}),{timeout:4000,maximumAge:20000})):{};const event={id:uid(),employeeId:employee.id,name:employee.nickname,date:today(),time:clock(),type,shift:employee.shift,lat:loc.lat??null,lng:loc.lng??null,gpsAccuracy:loc.accuracy??null,matchScore:null,status:'pending',note:'DEMO · ตรวจพบใบหน้าเท่านั้น ยังไม่มี face matching/PAD',createdAt:new Date().toISOString()};setDb(s=>({...s,events:[event,...s.events]}));setFaceMsg('บันทึกตัวอย่างในเครื่องแล้ว · ยังไม่ใช่การลงเวลาจริง');notify('โหมดเดโม: บันทึกไว้ในอุปกรณ์นี้เท่านั้น');if(type==='out'){try{speechSynthesis.speak(new SpeechSynthesisUtterance('ขอให้โชคดี'))}catch{}}stopCamera();setFaceState('idle')}
  function decide(evId,decision){setDb(s=>({...s,events:s.events.map(e=>e.id===evId?{...e,status:decision,reviewedBy:'DEMO Admin',reviewedAt:new Date().toISOString()}:e)}));notify('เปลี่ยนสถานะในข้อมูลเดโมเท่านั้น')}
  function addEmployee(e){e.preventDefault();if(!form.firstName.trim()||!form.nickname.trim())return;const emp={...form,id:`NV${String(Date.now()).slice(-5)}`,active:true,faceStatus:'ยังไม่ลงทะเบียน'};setDb(s=>({...s,employees:[...s.employees,emp]}));setForm({firstName:'',nickname:'',type:'รายเดือน',shift:'normal',note:''});notify('เพิ่มพนักงานในข้อมูลทดลองแล้ว')}
  function deactivateEmployee(id){setDb(s=>({...s,employees:s.employees.map(e=>e.id===id?{...e,active:false}:e)}));notify('ปิดใช้งานในข้อมูลทดลองแล้ว')}
  function addHoliday(e){e.preventDefault();if(!holidayForm.date||!holidayForm.name)return;setDb(s=>({...s,holidays:[...s.holidays,{...holidayForm,id:uid()}].sort((a,b)=>a.date.localeCompare(b.date))}));setHolidayForm({date:'',name:'',type:'บริษัท'});notify('เพิ่มวันหยุดในข้อมูลทดลองแล้ว')}
  function saveWorksite(e){e.preventDefault();notify('บันทึกสถานที่ใน Local Storage ของเดโมแล้ว')}
  function exportAttendance(){const rows=[['ชื่อพนักงาน','วันที่','เวลาเข้างาน','เวลาออกงาน','สาย (นาที)','กะ','OT 1.0x','OT 1.5x','OT 2.0x','OT 3.0x','รวมเวลาทำงาน','รวม OT','หมายเหตุ','สถานะ']];for(const emp of db.employees){const ev=db.events.filter(x=>x.employeeId===emp.id&&x.status==='approved');const cin=ev.find(x=>x.type==='in'),cout=ev.find(x=>x.type==='out');rows.push([emp.nickname,cin?.date||cout?.date||'',cin?.time||'',cout?.time||'','',shiftFor(db,emp.shift).name,'','','','','','',ev.some(x=>x.note?.startsWith('DEMO'))?'DEMO · LOCAL ONLY':'','DEMO'])}const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`NOVA_Attendance_${today()}.csv`;a.click();URL.revokeObjectURL(a.href)}
  function switchRole(v){stopCamera();setFaceState('idle');setDb(s=>({...s,role:v}));setTab('home')}
  function shiftOptions(){return db.shifts.map(s=><option value={s.id} key={s.id}>{s.name} ({s.start}–{s.end})</option>)}
  const approvedCount=db.events.filter(e=>e.status==='approved'&&e.date===today()).length;
  return <div className="app">
    <header className="top"><div className="brand"><div className="logo">N</div><div><b>NOVA <span>ATTENDANCE</span></b><small>VERSION 2 · BETA</small></div></div><div className="top-right"><span className="demo-chip"><i/> BETA DEMO</span><span className="top-time">{clock()}</span></div></header>
    <main className="content">
      <div className="page-intro"><div><small>{new Intl.DateTimeFormat('th-TH',{timeZone:'Asia/Bangkok',weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(now)}</small><h1>{tab==='home'?(isAdmin?'ภาพรวม NOVA':'หน้าหลัก'):tab==='history'?'ประวัติของฉัน':'ตั้งค่า'}</h1></div><div className="coco" aria-label="โกโก้"><span/><i/><i/><b/></div></div>
      <div className="role-row"><span><ShieldCheck size={14}/>{roleNames[role]}</span><select value={role} onChange={e=>switchRole(e.target.value)} aria-label="เลือกบทบาทเดโม"><option value="user">พนักงาน · Demo</option><option value="peopleadmin">Admin เพิ่มพนักงาน · Demo</option><option value="superadmin">Admin ขั้นสูง · Demo</option></select></div>
      {tab==='home'&&!isAdmin&&<section className="employee-home">
        <div className="hello"><div><small>ยินดีต้อนรับ</small><h2>{employee?.nickname||'พนักงาน'} 👋</h2><p>{shiftFor(db,employee?.shift).name} · {shiftFor(db,employee?.shift).start}–{shiftFor(db,employee?.shift).end}</p></div><div className="shift-mark"><Clock3 size={20}/></div></div>
        <div className={`camera-box ${faceState==='detected'?'is-detected':''}`}>{faceState==='camera'||faceState==='detected'?<><video ref={video} autoPlay muted playsInline/><div className="scan-frame"><span/><span/><span/><span/><div className="oval"/></div><div className="camera-status">{faceState==='detected'?'พบใบหน้า':'กำลังตรวจภาพ'}</div></>:<div className="camera-empty"><div className="face-icon"><ScanFace size={45}/></div><b>สแกนใบหน้าเข้า–ออกงาน</b><small>{cameraError||faceMsg}</small></div>}</div>
        <div className="face-status"><span className={`pulse ${faceState==='detected'?'ok':''}`}/><span>{faceMsg}</span></div>
        <div className="quality-note"><Fingerprint size={16}/><div><b>การตรวจในเบต้า 2</b><small>ตรวจพบใบหน้าเท่านั้น · ยังไม่ใช่การจับคู่ตัวตน คะแนน 70% และ PAD ยังไม่เปิด</small></div></div>
        <div className="scan-actions">{faceState==='camera'||faceState==='detected'?<><button className="primary" disabled={faceState!=='detected'} onClick={()=>captureEvent(mine.some(e=>e.type==='in'&&e.status!=='rejected')?'out':'in')}><ScanFace size={18}/>{mine.some(e=>e.type==='in'&&e.status!=='rejected')?'บันทึกตัวอย่างออกงาน':'บันทึกตัวอย่างเข้างาน'}</button><button className="secondary" onClick={()=>{stopCamera();setFaceState('idle')}}><X size={17}/></button></>:<button className="primary" onClick={startCamera}><Camera size={18}/>เปิดกล้อง</button>}</div>
        <div className="notice"><Wifi size={15}/> DEMO: ข้อมูลอยู่ในอุปกรณ์นี้ ไม่มีการเขียนลง Google Sheets</div>
        <section className="card"><div className="card-head"><div><small>วันนี้ · {today()}</small><h3>เวลาของฉัน</h3></div><CalendarDays size={18}/></div>{['in','out'].map(type=>{const row=mine.find(e=>e.type===type);return <div className="time-row" key={type}><span className={`event-icon ${type}`}>{type==='in'?<LogIn size={16}/>:<LogOut size={16}/>}</span><div><b>{type==='in'?'เข้างาน':'ออกงาน'}</b><small>{row?row.time:'ยังไม่มีรายการ'}</small></div>{row&&<span className={`pill ${row.note?.startsWith('DEMO')?'demo':row.status}`}>{row.note?.startsWith('DEMO')?'DEMO · '+(row.status==='pending'?'รออนุมัติ':row.status==='approved'?'อนุมัติเดโม':'ไม่อนุมัติเดโม'):row.status==='pending'?'รออนุมัติ':row.status==='approved'?'อนุมัติแล้ว':'ไม่อนุมัติ'}</span>}</div>})}</section>
      </section>}
      {tab==='home'&&isAdmin&&<AdminHome db={db} pending={pending} approvedCount={approvedCount} decide={decide} exportAttendance={exportAttendance} isSuper={isSuper}/>}
      {tab==='history'&&<HistoryView events={isAdmin?db.events:db.events.filter(e=>e.employeeId===employee?.id)} />}
      {tab==='settings'&&<SettingsView {...{db,setDb,isSuper,form,setForm,addEmployee,deactivateEmployee,holidayForm,setHolidayForm,addHoliday,saveWorksite,shiftOptions,notify}}/>}
    </main>
    <nav className="bottom-nav"><button className={tab==='history'?'active':''} onClick={()=>{stopCamera();setFaceState('idle');setTab('history')}}><History size={19}/><span>ประวัติของฉัน</span></button><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}><House size={19}/><span>หน้าหลัก</span></button><button className={tab==='settings'?'active':''} onClick={()=>{stopCamera();setFaceState('idle');setTab('settings')}}><Settings size={19}/><span>ตั้งค่า</span></button></nav>
    {toast&&<div className="toast"><Check size={15}/>{toast}</div>}
  </div>
}

function AdminHome({db,pending,approvedCount,decide,exportAttendance,isSuper}){return <div className="admin-home"><div className="admin-stats"><div className="stat"><Users/><small>พนักงาน</small><b>{db.employees.filter(e=>e.active).length}</b></div><div className="stat"><Clock3/><small>รออนุมัติ</small><b>{pending.length}</b></div><div className="stat"><BadgeCheck/><small>รับรองวันนี้</small><b>{approvedCount}</b></div></div><section className="card"><div className="card-head"><div><small>ADMIN REVIEW</small><h3>รายการรออนุมัติ</h3></div><span className="count">{pending.length}</span></div>{pending.length?pending.map(e=><div className="approval" key={e.id}><div className="initial">{e.name?.slice(0,1)}</div><div className="approval-main"><b>{e.name}</b><small>{e.date} · {e.time} · {e.type==='in'?'เข้างาน':'ออกงาน'} · {e.note?.startsWith('DEMO')?'DEMO':''}</small></div>{isSuper?<><button className="mini-btn" onClick={()=>decide(e.id,'approved')}>อนุมัติเดโม</button><button className="reject" onClick={()=>decide(e.id,'rejected')}><X size={15}/></button></>:<span className="pill pending">รอ Admin ขั้นสูง</span>}</div>):<div className="empty">ไม่มีรายการที่รออนุมัติ</div>}</section><section className="card"><div className="card-head"><div><small>DAILY REPORT</small><h3>ส่งออกรายงาน</h3></div><ArrowDownToLine size={18}/></div><p className="muted">CSV ใช้ตรวจรูปแบบคอลัมน์เท่านั้น ข้อมูลคำนวณยังเป็นเดโม</p><button className="outline full" onClick={exportAttendance}><ArrowDownToLine size={16}/> ดาวน์โหลด CSV ทดลอง</button></section><div className="notice"><Cloud size={15}/> LINE 06:00 และ Drive backup ยังไม่เชื่อมในเบต้านี้</div></div>}

function HistoryView({events}){const ordered=[...events].sort((a,b)=>`${b.date} ${b.time}`.localeCompare(`${a.date} ${a.time}`));return <section className="card history-card"><div className="card-head"><div><small>ATTENDANCE HISTORY</small><h3>ประวัติลงเวลา</h3></div><History size={18}/></div>{ordered.length?ordered.map(e=><div className="history-row" key={e.id}><span className={`event-icon ${e.type}`}>{e.type==='in'?<LogIn size={16}/>:<LogOut size={16}/>}</span><div><b>{e.name} · {e.type==='in'?'เข้างาน':'ออกงาน'}</b><small>{e.date} · {e.time} · {e.note?.startsWith('DEMO')?'DEMO':roleNames.user}</small></div><span className={`pill ${e.status}`}>{e.note?.startsWith('DEMO')?'DEMO · '+(e.status==='pending'?'รออนุมัติ':e.status==='approved'?'อนุมัติเดโม':'ไม่อนุมัติเดโม'):e.status==='pending'?'รออนุมัติ':e.status==='approved'?'รับรอง':'ไม่รับรอง'}</span></div>):<div className="empty">ยังไม่มีประวัติลงเวลา</div>}</section>}

function SettingsView(p){const {db,setDb,isSuper,form,setForm,addEmployee,deactivateEmployee,holidayForm,setHolidayForm,addHoliday,saveWorksite,shiftOptions,notify}=p;return <div className="settings-page"><section className="card account-card"><div className="account-avatar"><UserRound/></div><div><small>บัญชีทดลอง</small><b>{roleNames[db.role]}</b><span>{db.employees.find(e=>e.id===db.activeEmployeeId)?.nickname||'NOVA'}</span></div><span className="pill demo">BETA</span></section>
  {db.role==='user'&&<section className="card"><div className="card-head"><div><small>ACCOUNT</small><h3>บัญชีพนักงาน</h3></div><UserRound size={18}/></div><label>เลือกพนักงาน<select value={db.activeEmployeeId} onChange={e=>setDb(s=>({...s,activeEmployeeId:e.target.value}))}>{db.employees.filter(e=>e.active).map(e=><option key={e.id} value={e.id}>{e.nickname} · {e.id}</option>)}</select></label><div className="notice">เข้าสู่ระบบจริงและเปลี่ยนรหัสผ่านยังไม่เชื่อมใน Beta 2</div></section>}
  {db.role==='peopleadmin'&&<EmployeeManager {...{db,setDb,form,setForm,addEmployee,deactivateEmployee,shiftOptions,notify,canDelete:false}}/>}
  {isSuper&&<><EmployeeManager {...{db,setDb,form,setForm,addEmployee,deactivateEmployee,shiftOptions,notify,canDelete:true}}/><WorksiteCard {...{db,setDb,saveWorksite}}/><ShiftCard {...{db,setDb,notify}}/><HolidayCard {...{db,setDb,holidayForm,setHolidayForm,addHoliday}}/><section className="card"><div className="card-head"><div><small>DATA EXPORT</small><h3>ดาวน์โหลดข้อมูล</h3></div><ArrowDownToLine size={18}/></div><button className="outline full" onClick={()=>notify('ส่งออก CSV ผ่านหน้า Admin ภาพรวม')}>ส่งออกข้อมูลลงเวลา</button></section></>}
  {db.role==='peopleadmin'&&<section className="card"><div className="card-head"><div><small>FACE ENROLLMENT</small><h3>ลงทะเบียนใบหน้า</h3></div><Fingerprint size={18}/></div><div className="notice">บันทึกสถานะเท่านั้น · Face Descriptor 128D ยังไม่ถูกสร้างหรือจัดเก็บในรุ่นนี้</div></section>}
  <section className="card system-info"><div className="card-head"><div><small>SYSTEM STATUS</small><h3>สถานะการเชื่อมต่อ</h3></div><Activity size={18}/></div><div className="status-line"><span>Face API / identity matching</span><b>ยังไม่เชื่อม</b></div><div className="status-line"><span>Google Sheets API</span><b>ยังไม่เชื่อม</b></div><div className="status-line"><span>LINE / Drive backup</span><b>ยังไม่เชื่อม</b></div></section>
  </div>}

function EmployeeManager(p){const {db,setDb,form,setForm,addEmployee,deactivateEmployee,shiftOptions,notify,canDelete}=p;return <section className="card"><div className="card-head"><div><small>EMPLOYEE DIRECTORY</small><h3>{canDelete?'จัดการพนักงาน':'เพิ่มพนักงาน'}</h3></div><Users size={18}/></div><form className="employee-form" onSubmit={addEmployee}><label>ชื่อจริง *<input value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})} required/></label><label>ชื่อเล่น *<input value={form.nickname} onChange={e=>setForm({...form,nickname:e.target.value})} required/></label><label>ประเภทพนักงาน *<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>รายเดือน</option><option>รายวัน</option><option>พาร์ตไทม์</option><option>ฝึกงาน</option></select></label><label>กะ *<select value={form.shift} onChange={e=>setForm({...form,shift:e.target.value})}>{shiftOptions()}</select></label><label className="wide">หมายเหตุ<textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><div className="face-enroll"><Fingerprint size={17}/><div><b>Face Descriptor (128D JSON)</b><small>ยังไม่สร้าง descriptor ในเบต้านี้ · ต้องเชื่อม Face API ก่อน</small></div><button type="button" className="mini-btn" onClick={()=>notify('Face enrollment ยังปิดอยู่ใน Beta 2')}>เพิ่มใบหน้า</button></div><button className="primary wide" type="submit"><Plus size={17}/>เพิ่มและบันทึกพนักงาน</button></form><div className="employee-list">{db.employees.map(e=><div className={`employee-row ${!e.active?'inactive':''}`} key={e.id}><div className="initial">{e.nickname.slice(0,1)}</div><div><b>{e.firstName} ({e.nickname})</b><small>{e.id} · {e.type} · {shiftFor(db,e.shift).name} · {e.faceStatus}</small></div>{canDelete&&e.active&&<button className="reject" title="ปิดใช้งาน" onClick={()=>deactivateEmployee(e.id)}><X size={15}/></button>}</div>)}</div></section>}

function WorksiteCard({db,setDb,saveWorksite}){return <form className="card" onSubmit={saveWorksite}><div className="card-head"><div><small>WORKSITE</small><h3>สถานที่ทำงาน</h3></div><MapPin size={18}/></div><label>ชื่อสถานที่<input value={db.settings.worksiteName} onChange={e=>setDb(s=>({...s,settings:{...s.settings,worksiteName:e.target.value}}))}/></label><div className="two-col"><label>Latitude<input inputMode="decimal" value={db.settings.latitude} onChange={e=>setDb(s=>({...s,settings:{...s.settings,latitude:e.target.value}}))} placeholder="เช่น 13.7563"/></label><label>Longitude<input inputMode="decimal" value={db.settings.longitude} onChange={e=>setDb(s=>({...s,settings:{...s.settings,longitude:e.target.value}}))} placeholder="เช่น 100.5018"/></label></div><label>Allowed Radius (KM)<input inputMode="decimal" value={db.settings.radiusKm} onChange={e=>setDb(s=>({...s,settings:{...s.settings,radiusKm:e.target.value}}))}/></label><button className="outline full"><Check size={16}/>บันทึกสถานที่ (เดโม)</button></form>}

function ShiftCard({db,setDb,notify}){return <section className="card"><div className="card-head"><div><small>SHIFT SETTINGS</small><h3>กะและเวลาทำงาน</h3></div><Clock3 size={18}/></div>{db.shifts.map((shift,i)=><div className="shift-edit" key={shift.id}><b>{shift.name}</b><div className="two-col"><label>เริ่ม<input type="time" value={shift.start} onChange={e=>setDb(s=>({...s,shifts:s.shifts.map((x,j)=>i===j?{...x,start:e.target.value}:x)}))}/></label><label>เลิก<input type="time" value={shift.end} onChange={e=>setDb(s=>({...s,shifts:s.shifts.map((x,j)=>i===j?{...x,end:e.target.value}:x)}))}/></label></div></div>)}<p className="muted">ผ่อนผัน 9 นาที · นาที 10–15 คิด 15 นาที · นาที 16–20 คิด 30 นาที</p><button className="outline full" onClick={()=>notify('บันทึกกะในข้อมูลทดลองแล้ว')}>บันทึกกะ</button></section>}

function HolidayCard(p){const {db,setDb,holidayForm,setHolidayForm,addHoliday}=p;return <section className="card"><div className="card-head"><div><small>ANNUAL CALENDAR</small><h3>ปฏิทินวันหยุดประจำปี</h3></div><CalendarDays size={18}/></div><form className="holiday-form" onSubmit={addHoliday}><label>วันที่<input type="date" value={holidayForm.date} onChange={e=>setHolidayForm({...holidayForm,date:e.target.value})} required/></label><label>ชื่อวันหยุด<input value={holidayForm.name} onChange={e=>setHolidayForm({...holidayForm,name:e.target.value})} required/></label><label>ประเภท<select value={holidayForm.type} onChange={e=>setHolidayForm({...holidayForm,type:e.target.value})}><option>บริษัท</option><option>นักขัตฤกษ์</option><option>วันหยุดพิเศษ</option></select></label><button className="primary"><Plus size={16}/>เพิ่มวันหยุด</button></form>{db.holidays.length?db.holidays.map(h=><div className="holiday-row" key={h.id}><CalendarDays size={15}/><b>{h.date}</b><span>{h.name}</span><small>{h.type}</small><button className="reject" onClick={()=>setDb(s=>({...s,holidays:s.holidays.filter(x=>x.id!==h.id)}))}><X size={14}/></button></div>):<div className="empty">ยังไม่มีวันหยุดในปฏิทิน</div>}</section>}

createRoot(document.getElementById('root')).render(<App/>);
